name: Trigger News Scraper

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

jobs:
  trigger-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Call the cron job endpoint
        run: |
          curl --request GET \
          --url '${{ secrets.DEPLOYMENT_URL }}/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}' 